# Generated by Django 2.2.6 on 2021-01-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0008_delete_dummyassistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newactivitycreated',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
