# Generated by Django 2.2.6 on 2020-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('error', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'failed statement',
            },
        ),
        migrations.CreateModel(
            name='ProcessedStatement',
            fields=[
                ('statement_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'processed statement',
            },
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('course', models.IntegerField()),
                ('job_type', models.CharField(choices=[('early', 'early'), ('late', 'late'), ('inactive', 'inactive')], max_length=20)),
                ('args_json', models.TextField(default='undefined')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentNotificationSent',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('early', 'early'), ('late', 'late')], max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAssignmentOfCourse',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('early', 'early'), ('late', 'late')], max_length=20)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InactivityNotificationSent',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('args_json', models.TextField(default='{}')),
            ],
        ),
    ]
