# Generated by Django 2.2.6 on 2020-12-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='course',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='job_type',
            field=models.CharField(choices=[('inactive', 'inactive'), ('updatefirstdeadlines', 'updatefirstdeadlines'), ('assignment_check', 'assignment_check')], max_length=20),
        ),
    ]
